SELECT * FROM IBSC_USER
DROP TABLE IBSC_USER

SELECT * FROM IBSC_Training
DROP TABLE IBSC_Training

SELECT * FROM IBSC_User_Training
DROP TABLE IBSC_User_Training

SELECT * FROM IBSC_Documents
DROP TABLE IBSC_Documents

SELECT * FROM IBSC_OB_MASTER
DROP TABLE IBSC_OB_MASTER

SELECT * FROM IBSC_OB_USERS
DROP TABLE IBSC_OB_USERS